// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'app/config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform(config),
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(AppConfig config) {
    final isStaging = config.isStaging;
    if (kIsWeb) {
      return isStaging ? webStaging : webProduction;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isStaging ? androidStaging : androidProduction;
      case TargetPlatform.iOS:
        return isStaging ? iosStaging : iosProduction;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─────────────────────────────────────────────────────────────
  // Production Configurations (Project ID: edunova-aabd1)
  // ─────────────────────────────────────────────────────────────

  static const FirebaseOptions webProduction = FirebaseOptions(
    apiKey: 'AIzaSyBJwoCiblcaVRCbo66QMi7om02PPniP0SU',
    appId: '1:199517096075:web:52c9a30fd512ac98d8ac8e',
    messagingSenderId: '199517096075',
    projectId: 'edunova-aabd1',
    authDomain: 'edunova-aabd1.firebaseapp.com',
    storageBucket: 'edunova-aabd1.firebasestorage.app',
    measurementId: 'G-7RPFGSX9NF',
  );

  static const FirebaseOptions androidProduction = FirebaseOptions(
    apiKey: 'AIzaSyDq4HU94VNTjko3xtJkeNIeEYd-26f_yYk',
    appId: '1:199517096075:android:bcc88158174b9458d8ac8e',
    messagingSenderId: '199517096075',
    projectId: 'edunova-aabd1',
    storageBucket: 'edunova-aabd1.firebasestorage.app',
  );

  static const FirebaseOptions iosProduction = FirebaseOptions(
    apiKey: 'AIzaSyBMQgesmz1l6VMypilyItWfCIQ5QZe3S-Y',
    appId: '1:199517096075:ios:f9060b679be5a639d8ac8e',
    messagingSenderId: '199517096075',
    projectId: 'edunova-aabd1',
    storageBucket: 'edunova-aabd1.firebasestorage.app',
    iosBundleId: 'com.edunova.app',
  );

  // ─────────────────────────────────────────────────────────────
  // Staging Configurations (Project ID: intellia237-staging)
  // ─────────────────────────────────────────────────────────────

  static const FirebaseOptions webStaging = FirebaseOptions(
    apiKey: 'AIzaSyCeCQAnnfHhgNNch5fTScQFEpESP_D0Xl4',
    appId: '1:343680388379:web:32f9a30fd512ac98d8ac8e',
    messagingSenderId: '343680388379',
    projectId: 'intellia237-staging',
    authDomain: 'intellia237-staging.firebaseapp.com',
    storageBucket: 'intellia237-staging.firebasestorage.app',
  );

  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyCeCQAnnfHhgNNch5fTScQFEpESP_D0Xl4',
    appId: '1:343680388379:android:29a9a0035289f13078d7be',
    messagingSenderId: '343680388379',
    projectId: 'intellia237-staging',
    storageBucket: 'intellia237-staging.firebasestorage.app',
  );

  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'AIzaSyCeCQAnnfHhgNNch5fTScQFEpESP_D0Xl4',
    appId: '1:343680388379:ios:18fa90035289f13078d7be',
    messagingSenderId: '343680388379',
    projectId: 'intellia237-staging',
    storageBucket: 'intellia237-staging.firebasestorage.app',
    iosBundleId: 'com.intellia237.app.staging',
  );
}
