// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwoCiblcaVRCbo66QMi7om02PPniP0SU',
    appId: '1:199517096075:web:52c9a30fd512ac98d8ac8e',
    messagingSenderId: '199517096075',
    projectId: 'edunova-aabd1',
    authDomain: 'edunova-aabd1.firebaseapp.com',
    storageBucket: 'edunova-aabd1.firebasestorage.app',
    measurementId: 'G-7RPFGSX9NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4HU94VNTjko3xtJkeNIeEYd-26f_yYk',
    appId: '1:199517096075:android:bcc88158174b9458d8ac8e',
    messagingSenderId: '199517096075',
    projectId: 'edunova-aabd1',
    storageBucket: 'edunova-aabd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQgesmz1l6VMypilyItWfCIQ5QZe3S-Y',
    appId: '1:199517096075:ios:f9060b679be5a639d8ac8e',
    messagingSenderId: '199517096075',
    projectId: 'edunova-aabd1',
    storageBucket: 'edunova-aabd1.firebasestorage.app',
    iosBundleId: 'com.edunova.app',
  );

}